# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o1PICyN3Y1st-g-mKitaJnHDRCrRwaq2
"""

import pandas as pd
import numpy as np
import matplotlib as maplib

from google.colab import files
uploaded = files.upload()

df1 = pd.read_csv("GDP_.csv")

df1.head

from google.colab import files
uploaded = files.upload()

df2 = pd.read_csv("Inflation-rate_.csv")

df2.head

df2[df2.columns[1:]] = df2[df2.columns[1:]].replace('[%,]', '', regex=True)

df2.head

float("3,000%".replace("%", ""))

df2.info()



df2.dtypes

df2 = df2.convert_objects(convert_numeric=True)

.astype(float)

df2["Australia"] = pd.to_numeric(df2["Australia"])

df2["Austria"] = pd.to_numeric(df2["Austria"])

df2["Brazil"] = pd.to_numeric(df2["Brazil"])

df2["Germany"] = pd.to_numeric(df2["Germany"])

df2["Russia"] = pd.to_numeric(df2["Russia"])

df2["USA"] = pd.to_numeric(df2["USA"])

df2.info()



,"Austria", "Germany", "Brazil", "Russia", "USA"